#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/permissionTest?characterEncoding=UTF-8
    username: root
    password: 1234

#    druid:
#      initialSize: 1 #初始化连接数量
#      minIdel: 10 #最小空闲连接数
#      maxActive: 20 #最大并发连接数
#      maxWait: 60000 #配置获取连接等待超时的时间,单位毫秒
#      db.removeAbandoned: true #超过时间限制是否回收
#      db.removeAbandonedTimeout: 30000 #超过时间限制多长,单位毫秒
#      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒，当连接数小于最小配置则重新创建连接
#      minEvictionRunsMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
#      validationQuery: SELECT 1 FROM DUAL #检测使用语句
#      testWhileIdle: true #申请连接的时候检测,每30s会取出三条连接用下面的validationQuery进行测试，测试不成功则销毁连接，连接数小于最小配置则重新创建连接
#      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
#      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
#      poolPreparedStatements: false #打开PSCache，并且指定每个连接上PSCache的大小(备注: 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。)
#      maxPoolPreparedStatementPerConnectionSize: 20 #启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
#      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      connectionProperties: true
  #    druid.stat.slowSqlMillis: 2
  #    druid.stat.mergeSql: true
  #    spring.datasource.useGlobalDataSourceStat: true






